### ISSUE TITLE
test-drive shortcode visible in website. 

### ISSUE THREAD

**Issue by eliocamp** [tidymodels/tidymodels.org#81] opened 2024-10-19 00:45 UTC
I hope this is the correct repo to report this. On the website articles show a strange ` {{< test-drive "https://rstudio.cloud/project/2674862" >}} ` string, which I suspect is some defunct shortcode:

![image](https://github.com/user-attachments/assets/3db7fc46-f590-497a-a069-7b951eea367c)

I think it's present in all five Get Started articles, for example: https://www.tidymodels.org/start/models/

**Comment by hfrick** [comment] 2024-10-21 08:07
Hi @eliocamp 👋 Thanks for reporting this! This is absolutely the right repo. I'm going to close this issue though as a duplicate of #62

**Closed as completed by hfrick** 2024-10-21 08:07 UTC
