### ISSUE TITLE
Bug in package list in the find parsnip model section

### ISSUE THREAD

**Issue by topepo** [tidymodels/tidymodels.org#43] opened 2023-10-18 14:41 UTC
At [`https://www.tidymodels.org/find/parsnip/`](https://www.tidymodels.org/find/parsnip/), the `package` column is either "parsnip" or "modeltime".

**Comment by EmilHvitfeldt** [comment] 2023-10-18 15:55
duplicate of https://github.com/tidymodels/tidymodels.org/issues/32

**Closed as completed** 2023-10-18 18:42 UTC
